import sys
from typing import Annotated

from pydantic import BaseModel, Field

from cursed_vibing_on_the_fly import ai_implement

# Importing cache to inspect stats
from cursed_vibing_on_the_fly.core import _implementation_cache


# ==========================================
# BARE DEFINITIONS (No docs, no type hints)
# ==========================================


@ai_implement
def check_if_number_is_prime(n):
    pass


@ai_implement
def check_if_number_is_odd(n):
    pass


@ai_implement
def calculate_sum(a, b):
    pass


# ==========================================
# RICH DEFINITIONS (Docs + Type hints)
# ==========================================


# Example 1: Primality
@ai_implement
def check_if_integer_is_prime(n: int) -> bool:
    """Check if n is a prime number."""
    pass


# Example 2: Even/Odd
@ai_implement
def check_is_odd(n: int) -> bool:
    """Check if the number is odd."""
    pass


# Example 3: Sum
@ai_implement
def calculate_sum_of_numbers(a: int, b: int) -> int:
    """Calculate the sum of two integers."""
    pass


def run_example(func, args, expected_desc=""):
    name = func.__name__
    print(f"\n👉 Running {name} with args {args}")
    try:
        result = func(*args)
        print(f"   ✅ Result: {result}")

        # Look up stats
        if name in _implementation_cache:
            real_func = _implementation_cache[name]
            if hasattr(real_func, "_ai_stats"):
                attempts = real_func._ai_stats["attempts"]
                print(f"   📊 Attempts: {attempts}")
            else:
                print("   📊 Stats not available")
        else:
            print("   📊 Stats not found in cache")

    except Exception as e:
        print(f"   ❌ Failed: {e}")


if __name__ == "__main__":
    print("=" * 80)
    print("⚠️ WARNING! ⚠️")
    print()
    print(
        "This script will EXECUTE UNVERIFIED CODE generated by an LLM on your machine."
    )
    print("This is potentially dangerous and always stupid.")
    print("Ensure you are running this in a safe environment.")
    print("=" * 80)

    response = input("\nType 'continue' to proceed: ")
    if response.lower() != "continue":
        print("Aborting.")
        sys.exit(1)

    print("\n" + "=" * 60)
    print("TESTING AI-IMPLEMENTED FUNCTIONS")
    print("=" * 60)

    # 1. Primality
    print(f"\n--- 1. Primality Test ---")
    run_example(check_if_number_is_prime, (17,), "Bare definition")
    run_example(check_if_integer_is_prime, (17,), "Rich definition")

    # 2. Even/Odd
    print(f"\n--- 2. Even/Odd Test ---")
    run_example(check_if_number_is_odd, (3,), "Bare definition")
    run_example(check_is_odd, (3,), "Rich definition")

    # 3. Sum
    print(f"\n--- 3. Sum Test ---")
    run_example(calculate_sum, (10, 20), "Bare definition")
    run_example(calculate_sum_of_numbers, (10, 20), "Rich definition")
