import sys
from typing import Annotated, Union

from pydantic import BaseModel, Field

from cursed_vibing_on_the_fly import ai_implement

# Importing caches to inspect stats
from cursed_vibing_on_the_fly.core import _implementation_cache, _stats_cache


# ==========================================
# BARE DEFINITIONS (No docs, no type hints)
# ==========================================


@ai_implement
def check_if_number_is_prime(n):
    pass


@ai_implement
def check_if_number_is_odd(n):
    pass


@ai_implement
def calculate_sum(a, b):
    pass


# ==========================================
# RICH DEFINITIONS (Docs + Type hints)
# ==========================================


# Example 1: Primality
@ai_implement
def check_if_integer_is_prime(n: int) -> bool:
    """Check if n is a prime number."""
    pass


# Example 2: Even/Odd
@ai_implement
def check_is_odd(n: int) -> bool:
    """Check if the number is odd."""
    pass


# Example 3: Sum
@ai_implement
def calculate_sum_of_numbers(a: int, b: int) -> int:
    """Calculate the sum of two integers."""
    pass


# Example 4: Round float
@ai_implement
def round_float(number):
    """Rounds a given float to the nearest integer."""
    pass


# Example 5: String equals number
@ai_implement
def check_if_string_equals_number(
    string_input: str, comparison_number: Union[float, int]
) -> bool:
    """
    This function tries to parse a string into a float or int and then see if the value equals `comparison_number`.
    """
    pass


# Track execution results for summary
execution_log = []


def run_example(func, args, expected_desc=""):
    name = func.__name__
    print(f"\n👉 Running {name} with args {args}")

    result_status = "FAILED"
    attempts = 0

    try:
        result = func(*args)
        print(f"   ✅ Result: {result}")
        result_status = "SUCCESS"

        # Look up stats (always available in _stats_cache, regardless of caching setting)
        if name in _stats_cache:
            attempts = _stats_cache[name]["attempts"]
            print(f"   📊 Attempts: {attempts}")
        elif name in _implementation_cache:
            real_func = _implementation_cache[name]
            if hasattr(real_func, "_ai_stats"):
                attempts = real_func._ai_stats["attempts"]
                print(f"   📊 Attempts: {attempts}")
            else:
                attempts = "?"
                print("   📊 Stats not available")
        else:
            attempts = "?"
            print("   📊 Stats not available")

    except Exception as e:
        print(f"   ❌ Failed: {e}")
        result_status = "ERROR"
        # Check for stats even on failure (stored before raising exception)
        if name in _stats_cache:
            attempts = _stats_cache[name]["attempts"]
            print(f"   📊 Attempts: {attempts}")

    execution_log.append(
        {
            "function": name,
            "description": expected_desc,
            "status": result_status,
            "attempts": attempts,
        }
    )


def print_summary():
    print("\n" + "=" * 80)
    print("📢 EXECUTION SUMMARY")
    print("=" * 80)
    print(f"{'FUNCTION':<35} | {'STATUS':<10} | {'ATTEMPTS':<10} | {'DESCRIPTION'}")
    print("-" * 80)

    for entry in execution_log:
        print(
            f"{entry['function']:<35} | {entry['status']:<10} | {str(entry['attempts']):<10} | {entry['description']}"
        )
    print("=" * 80 + "\n")


if __name__ == "__main__":
    print("=" * 80)
    print("⚠️ WARNING! ⚠️")
    print()
    print(
        "This script will EXECUTE UNVERIFIED CODE generated by an LLM on your machine."
    )
    print("This is potentially dangerous and always stupid.")
    print("Ensure you are running this in a safe environment.")
    print("=" * 80)

    response = input("\nType 'continue' to proceed: ")
    if response.lower() != "continue":
        print("Aborting.")
        sys.exit(1)

    print("\n" + "=" * 60)
    print("TESTING AI-IMPLEMENTED FUNCTIONS")
    print("=" * 60)

    # 1. Primality
    print(f"\n--- 1. Primality Test ---")
    run_example(check_if_number_is_prime, (17,), "Bare definition")
    run_example(check_if_integer_is_prime, (17,), "Rich definition")

    # 2. Even/Odd
    print(f"\n--- 2. Even/Odd Test ---")
    run_example(check_if_number_is_odd, (3,), "Bare definition")
    run_example(check_is_odd, (3,), "Rich definition")

    # 3. Sum
    print(f"\n--- 3. Sum Test ---")
    run_example(calculate_sum, (10, 20), "Bare definition")
    run_example(calculate_sum_of_numbers, (10, 20), "Rich definition")

    # 4. Misc from README
    print(f"\n--- 4. Misc Examples from README ---")
    run_example(round_float, (3.7,), "Docstring only")
    run_example(check_if_string_equals_number, ("10.5", 10.5), "Complex typing")

    print_summary()
